dependencies:
  - type: olm.package
    value:
      packageName: openshift-pipelines-operator-rh
      version: ">=1.15.0"
  - type: olm.package
    value:
      packageName: openshift-gitops-operator
      version: ">=1.15.0"
  - type: olm.package
    value:
      packageName: external-secrets-operator
      version: ">=0.9.5"
